"""Correct typo in Requirements.skill_needed

Revision ID: cca629c1fd88
Revises: ade174bcfe86
Create Date: 2025-06-18 16:18:27.411779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca629c1fd88'
down_revision = 'ade174bcfe86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_needed', sa.String(length=100), nullable=True))
        batch_op.drop_column('skill_neded')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_neded', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('skill_needed')

    # ### end Alembic commands ###
